import { createClient } from "@supabase/supabase-js";
import type { AuditLog } from "./export";

/** All fields required to create an audit log entry (id and created_at are generated by the DB). */
export type CreateAuditLogEntry = Omit<AuditLog, "id" | "created_at">;

/**
 * Fields that warrant special handling in audit logs because they contain
 * personally-identifiable or security-sensitive data.
 */
export const SENSITIVE_FIELDS = new Set(["email", "password", "password_hash"]);

function createServerClient() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL!;
  // Prefer service role key for server-side writes so RLS does not block inserts.
  // Falls back to anon key so the module loads in environments without service key configured.
  const key =
    process.env.SUPABASE_SERVICE_ROLE_KEY ??
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
  return createClient(url, key);
}

/**
 * Writes a single audit log entry to the database.
 *
 * This function is intentionally non-throwing — any error is caught and
 * written to console so that an audit failure never disrupts the auth flow.
 */
export async function logAuditEvent(
  entry: CreateAuditLogEntry
): Promise<void> {
  try {
    const supabase = createServerClient();
    const { error } = await supabase.from("audit_logs").insert(entry);

    if (error) {
      console.error(
        JSON.stringify({
          ts: new Date().toISOString(),
          service: "audit-logger",
          event: "insert_failed",
          error: error.message,
          action: entry.action,
          resource_type: entry.resource_type,
          organization_id: entry.organization_id,
        })
      );
    }
  } catch (err) {
    console.error(
      JSON.stringify({
        ts: new Date().toISOString(),
        service: "audit-logger",
        event: "unexpected_error",
        error: err instanceof Error ? err.message : String(err),
      })
    );
  }
}

/**
 * Dispatches an audit event without blocking the caller.
 *
 * Use this in synchronous hook contexts where you cannot await. The returned
 * Promise is intentionally not awaited — errors are handled inside logAuditEvent.
 */
export function logAuditEventFireAndForget(
  entry: CreateAuditLogEntry
): void {
  void logAuditEvent(entry);
}

/**
 * Returns true if any key in the changes map is a sensitive field
 * (e.g. email address change).
 */
export function hasSensitiveChanges(
  changes: Record<string, { before: unknown; after: unknown }> | null
): boolean {
  if (!changes) return false;
  return Object.keys(changes).some((key) => SENSITIVE_FIELDS.has(key));
}

/**
 * Builds a changes map from two plain objects, capturing only the fields
 * that actually differ between before and after state.
 */
export function buildChangesMap(
  before: Record<string, unknown>,
  after: Record<string, unknown>
): Record<string, { before: unknown; after: unknown }> | null {
  const changes: Record<string, { before: unknown; after: unknown }> = {};

  const allKeys = new Set([...Object.keys(before), ...Object.keys(after)]);
  for (const key of allKeys) {
    if (before[key] !== after[key]) {
      changes[key] = { before: before[key] ?? null, after: after[key] ?? null };
    }
  }

  return Object.keys(changes).length > 0 ? changes : null;
}
