/**
 * Database-level TypeScript types for the module registration system.
 *
 * These types mirror the `modules` table columns. They use camelCase naming
 * per project convention while the underlying columns use snake_case.
 *
 * Note: Application-level types (ModuleManifest, RegisteredModule,
 * RolePermissions) live in `src/lib/modules/types.ts`.
 */

// ---------------------------------------------------------------------------
// modules table types
// ---------------------------------------------------------------------------

/**
 * A single row from the `modules` table.
 * Represents one module registered for a specific organization.
 */
export interface ModuleRow {
  /** Primary key UUID. */
  id: string;
  /** UUID of the organization this module is registered under. */
  organizationId: string;
  /**
   * Kebab-case identifier for the module. Unique within an organization.
   * Matches the pattern: ^[a-z0-9]+(-[a-z0-9]+)*$
   * @example "test-runner", "audit-logs", "integrations-engine"
   */
  moduleKey: string;
  /** Human-readable name displayed in the permissions UI. */
  displayName: string;
  /** Whether the module exposes a settings page that can be separately permission-gated. */
  hasSettings: boolean;
  /** ISO 8601 timestamp of when the row was created. */
  createdAt: string;
  /** ISO 8601 timestamp of the most recent update. */
  updatedAt: string;
}

/**
 * Data required to insert a new module row.
 * id, createdAt, and updatedAt are generated by the database.
 */
export type CreateModuleRow = Omit<ModuleRow, "id" | "createdAt" | "updatedAt">;

/**
 * Partial update payload for an existing module row.
 * Only displayName and hasSettings are mutable after registration.
 */
export interface UpdateModuleRow {
  /** New human-readable display name. Must be non-empty if provided. */
  displayName?: string;
  /** Toggle whether the module exposes a settings page. */
  hasSettings?: boolean;
}

/**
 * Composite key that uniquely identifies a module registration.
 * Used for lookups and upserts.
 */
export interface ModuleLookupKey {
  organizationId: string;
  moduleKey: string;
}
