/**
 * Database-level TypeScript types for the permission management system.
 *
 * These types mirror the `module_permissions` and `permission_audit_log`
 * database tables.  They use camelCase naming per project convention while
 * the underlying columns use snake_case.
 *
 * Note: Application-level permission types (role hierarchy, resolved
 * permissions, module manifests) live in `src/lib/permissions/types.ts`
 * and `src/lib/modules/types.ts`.
 */

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

/** The three roles in order of decreasing privilege (lowercase, matches DB). */
export type PermissionRole = "owner" | "admin" | "user";

/** The two boolean fields that make up the two-layer permission model. */
export type PermissionLevel = "feature_access" | "settings_access";

// ---------------------------------------------------------------------------
// module_permissions table types
// ---------------------------------------------------------------------------

/**
 * A single row from the `module_permissions` table.
 * Represents the effective two-layer permission for one org + module + role.
 */
export interface Permission {
  /** Primary key UUID. */
  id: string;
  /** The organization this permission belongs to. */
  organizationId: string;
  /** Kebab-case module identifier (e.g. "user-management"). */
  module: string;
  /** The role this permission applies to. */
  role: PermissionRole;
  /** Whether this role can access the module's feature at all. */
  featureAccess: boolean;
  /**
   * Whether this role can configure the module's settings.
   * Only meaningful when featureAccess is true; the database enforces
   * that settingsAccess cannot be true when featureAccess is false.
   */
  settingsAccess: boolean;
  /** ISO 8601 timestamp of when the row was created. */
  createdAt: string;
  /** ISO 8601 timestamp of the most recent update. */
  updatedAt: string;
}

/**
 * Payload for updating an existing permission row.
 * Both fields are optional — callers may update one or both at a time.
 * The database constraint ensures settingsAccess cannot be set to true
 * while featureAccess is false.
 */
export interface PermissionUpdate {
  featureAccess?: boolean;
  settingsAccess?: boolean;
}

/**
 * Parameters needed to identify a unique permission row
 * (the (organizationId, module, role) unique key).
 */
export interface PermissionLookupKey {
  organizationId: string;
  module: string;
  role: PermissionRole;
}

/**
 * Data required to create a new permission row (id, createdAt, updatedAt
 * are generated by the database).
 */
export type CreatePermission = Omit<Permission, "id" | "createdAt" | "updatedAt">;

// ---------------------------------------------------------------------------
// permission_audit_log table types
// ---------------------------------------------------------------------------

/**
 * A single row from the `permission_audit_log` table.
 * Captures one atomic permission toggle: who changed which boolean field,
 * on which module + role, from what value to what value.
 */
export interface PermissionAuditLogEntry {
  /** Primary key UUID. */
  id: string;
  /** The organization this log entry belongs to. */
  organizationId: string;
  /** Kebab-case module identifier. */
  module: string;
  /** The role whose permission was changed. */
  role: PermissionRole;
  /** ID of the user who made the change. */
  actorId: string;
  /** Email of the user who made the change (denormalized for readability). */
  actorEmail: string;
  /** Display name of the user who made the change. */
  actorName: string;
  /** Which permission layer was toggled. */
  changedField: PermissionLevel;
  /** The value before the change. */
  previousValue: boolean;
  /** The value after the change. */
  newValue: boolean;
  /** IP address of the request, if available. */
  ipAddress: string | null;
  /** User-agent string of the request, if available. */
  userAgent: string | null;
  /** ISO 8601 timestamp of when the change occurred. */
  createdAt: string;
}

/**
 * Data required to write a new audit log entry (id and createdAt are
 * generated by the database).
 */
export type CreatePermissionAuditLogEntry = Omit<
  PermissionAuditLogEntry,
  "id" | "createdAt"
>;

// ---------------------------------------------------------------------------
// Query / filter types
// ---------------------------------------------------------------------------

/**
 * Optional filters for querying the permission audit log.
 * All filters are combined with AND.
 */
export interface PermissionAuditLogFilters {
  /** Narrow to a specific module. */
  module?: string;
  /** Narrow to a specific role. */
  role?: PermissionRole;
  /** Narrow to changes made by a specific actor. */
  actorId?: string;
  /** Narrow to a specific permission level that was changed. */
  changedField?: PermissionLevel;
  /** Include only entries on or after this ISO 8601 date-time. */
  dateFrom?: string;
  /** Include only entries on or before this ISO 8601 date-time. */
  dateTo?: string;
}

/** Pagination parameters for audit log queries. */
export interface PaginationParams {
  page: number;
  pageSize: number;
}

/** Paginated result returned by audit log queries. */
export interface PaginatedPermissionAuditLog {
  data: PermissionAuditLogEntry[];
  /** Total number of rows matching the filters (for pagination UI). */
  total: number;
}
