/**
 * TypeScript types for the user management system.
 *
 * These types mirror the `users` and `invitations` database tables.
 * They use camelCase naming per project convention while the underlying
 * columns use snake_case.
 *
 * Note: Role values are capitalized ('Owner' | 'Admin' | 'User') to match
 * the `user_role` DB enum and the application-level UserRole type used
 * throughout the services layer.
 */

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

/** The three roles in order of decreasing privilege (capitalized, matches DB). */
export type UserRole = "Owner" | "Admin" | "User";

/** Lifecycle status of a user account within an organization. */
export type UserStatus = "active" | "invited" | "expired";

// ---------------------------------------------------------------------------
// users table types
// ---------------------------------------------------------------------------

/**
 * A single row from the `users` table.
 * Represents one user's membership and role within an organization.
 */
export interface User {
  /** Primary key UUID — matches the auth provider's user ID. */
  id: string;
  /** The organization this user belongs to. */
  organizationId: string;
  /** User's email address. Unique within an organization. */
  email: string;
  /** User's display name. */
  name: string;
  /** Role assigned to this user within the organization. */
  role: UserRole;
  /** Current lifecycle status of the user account. */
  status: UserStatus;
  /** ISO 8601 timestamp of when the row was created. */
  createdAt: string;
  /** ISO 8601 timestamp of the most recent update. */
  updatedAt: string;
}

/**
 * Payload for creating a new user row.
 * id, createdAt, and updatedAt are supplied by the caller (id from auth,
 * timestamps from the database default).
 */
export type CreateUser = Omit<User, "createdAt" | "updatedAt">;

/**
 * Fields that may be updated on an existing user row.
 */
export interface UpdateUser {
  name?: string;
  role?: UserRole;
  status?: UserStatus;
}

/**
 * Lightweight projection used in list views (omits timestamps for brevity).
 */
export type UserSummary = Pick<User, "id" | "email" | "name" | "role" | "status">;

// ---------------------------------------------------------------------------
// invitations table types
// ---------------------------------------------------------------------------

/**
 * A single row from the `invitations` table.
 * Tracks a pending or historical invitation sent to an email address.
 */
export interface Invitation {
  /** Primary key UUID. */
  id: string;
  /** The organization the invitee will join. */
  organizationId: string;
  /** Email address of the person being invited. */
  email: string;
  /** Role that will be assigned to the invitee upon acceptance. */
  role: UserRole;
  /** Auth user ID of the person who created the invitation. */
  invitedBy: string;
  /** Opaque random token included in the invitation link. */
  token: string;
  /** ISO 8601 timestamp after which the token is no longer valid. */
  expiresAt: string;
  /** ISO 8601 timestamp of acceptance; null means not yet accepted. */
  usedAt: string | null;
  /** ISO 8601 timestamp of when the invitation was created. */
  createdAt: string;
}

/**
 * Derived status of an invitation based on usedAt and expiresAt.
 */
export type InvitationStatus = "pending" | "accepted" | "expired";

/**
 * Invitation with its derived status attached (token omitted — never expose raw tokens).
 */
export type InvitationWithStatus = Omit<Invitation, "token"> & {
  status: InvitationStatus;
};

/**
 * Data required to create a new invitation row.
 * id and createdAt are generated by the database.
 * token, expiresAt, and usedAt are set by the application.
 */
export type CreateInvitation = Omit<Invitation, "id" | "createdAt">;

// ---------------------------------------------------------------------------
// Query / filter types
// ---------------------------------------------------------------------------

/**
 * Optional filters for querying users within an organization.
 */
export interface UserFilters {
  /** Narrow to a specific role. */
  role?: UserRole;
  /** Narrow to a specific account status. */
  status?: UserStatus;
  /** Case-insensitive partial match on email or name. */
  search?: string;
}

/**
 * Optional filters for querying invitations within an organization.
 */
export interface InvitationFilters {
  /** Narrow to a specific role. */
  role?: UserRole;
  /** Narrow to a derived status. */
  status?: InvitationStatus;
  /** Narrow to invitations created by a specific user. */
  invitedBy?: string;
}
